### ISSUE TITLE
Length of buff can cause issues

### ISSUE THREAD

**Issue by Ritsuna** [Cactuar87/Pathfinder-Aura-Share#1]
I have found that if the original buff's name is too long, it does not get spread out. Aura of Crushing Despair for example is too long and does not work, but Crushing Despair does work. I am not sure if other things like : causes issues.

**Comment by FionaBrightgrass** [comment]
I'll test this and take a look. Maybe there's a character limit.

**Comment by FionaBrightgrass** [comment]
Can you confirm if this is still occuring? I have a character with - : ' in their 40 character name and it's working with "Aura of Crushing Despair"
