### ISSUE TITLE
Aura Buffs are duplicated when moving through affected token's square.

### ISSUE THREAD

**Issue by TheGruntBox** [Cactuar87/Pathfinder-Aura-Share#14]
When a token with a shared aura moves into a square that has a recipient token, the buff is duplicated on the aura owner's sheet.
![image](https://github.com/FionaBrightgrass/Aura-Share/assets/162272404/ca8e9fb7-8d70-45d1-a7fb-0e3defde5c08)
After moving right with the arrow keys
![image](https://github.com/FionaBrightgrass/Aura-Share/assets/162272404/0513281a-3687-4c07-a933-3eb13fbe6c00)
This seems to only happen with affected tokens, the player token in the line-up does not duplicate buffs. The affected tokens also have multiple instances of the buff on their sheet, though this is expected behavior with 'Delete Auras' disabled.

**Comment by TheGruntBox** [comment]
After some more testing, enabling 'Delete Auras' partially mitigates the issue, though some buffs incorrectly remain activated.

**Comment by FionaBrightgrass** [comment]
interesting. I never really thought to put tokens in the same square. I'll take a look.

**Comment by FionaBrightgrass** [comment]
Alright. I figured the best way to resolve this was to set auras to distance: -1 when copied.  It should be resolved if you update.

**Comment by TheGruntBox** [comment]
Just tested after the update, issue is resolved!
