### ISSUE TITLE
Radius seems to orginate from Top Left Corner rather than center of token

### ISSUE THREAD

**Issue by Kazgaldun** [Cactuar87/Pathfinder-Aura-Share#15]
The radius in which the aura is applied appears to be measured from the top left corner of the token. It less noticeable on smaller tokens but on large+ enemies it becomes significantly more notable.
![AuraOriginPoint](https://github.com/FionaBrightgrass/Aura-Share/assets/163483131/b587fdfa-cbcf-43fe-a51f-a68fb86668db)

**Comment by FionaBrightgrass** [comment]
Adjusted. Thanks for the callout.
