### ISSUE TITLE
Feature Request: One Cast and Done

### ISSUE THREAD

**Issue by kenderbard** [Cactuar87/Pathfinder-Aura-Share#2]
Would love to be able to set a dictionary flag that lets me indicate that once used, to apply the buff to everyone within range and then be done; this would add more use for this module for things such as Area of Effect buffs (for example: casting Bless) that don't have a sustained need to stay in range.

I do understand that's outside the purview of this mod's intended purpose, though.

**Comment by FionaBrightgrass** [comment]
I'm looking into this idea. The module was coded with the actor being the center of the effect each turn. This would require a different approach, so it may take some time.

**Comment by dmrickey** [comment]
This can be done pretty easily with Noon's `useBuff` macro linked in the pf1 discord's pinned comments
