### ISSUE TITLE
Token Radius seems inconsistent

### ISSUE THREAD

**Issue by Fair-Strides** [Cactuar87/Pathfinder-Aura-Share#3]
I set up a simple Aura of Courage buff from a Paladin as a test with this module. I've configured it like so:

![image](https://github.com/FionaBrightgrass/Aura-Share/assets/72034470/38dc46ab-e83c-4bdd-a4d6-15592aa877b5)

My understanding is that this will keep the buff on while a token is within 10ft of the actor. This works here:

![image](https://github.com/FionaBrightgrass/Aura-Share/assets/72034470/a3378ea8-c1b2-4e05-9efd-0c4fe122a96d)

But not when inside the radius limit:

![image](https://github.com/FionaBrightgrass/Aura-Share/assets/72034470/e6a6c93e-3a41-491d-adc4-40dfb2768d9c)

**Comment by Fair-Strides** [comment]
Okay, now it might be working. I accidentally had two copies of a token on the map that might have been linked?

But it might not catching the outer diagonals. I've shown the aura using the Token Auras module at a 10ft radius:
![image](https://github.com/FionaBrightgrass/Aura-Share/assets/72034470/b1f27dfd-d9ad-4a6d-ad82-b6d840743ba9)

**Comment by FionaBrightgrass** [comment]
Yeah it uses foundry's built in distance for the angles. I'm not sure how
it calculates it but it doesn't seem to go off the center of the token. I
was thinking about just nudging it a little.

**Comment by FionaBrightgrass** [comment]
I added a nudging feature that may help with this. If you want to grab more corner tiles.
