### ISSUE TITLE
Error when updating an actor

### ISSUE THREAD

**Issue by dmrickey** [Cactuar87/Pathfinder-Aura-Share#4]
![image](https://github.com/FionaBrightgrass/Aura-Share/assets/3664822/9fa31301-42ac-4527-878b-8d9285f0b46a)

This hook is checking for `update.system.attributes.hp`. This property only exists on the update object if it's the actor's hp that is being updated. Updating anything else about the actor throws an exception.

**Comment by FionaBrightgrass** [comment]
I'm looking at it now, because this was something that I had fixed already. Are you on the latest version?

![image](https://github.com/FionaBrightgrass/Aura-Share/assets/91420423/ca5449f6-0e7b-4737-8d92-b44129bb5849)

**Comment by FionaBrightgrass** [comment]
Apologies, looks like you had reported this in the first place I just fixed it before your post. Thanks.
