### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by Telain** [Cactuar87/Pathfinder-Aura-Share#5]
Foundry showed a method being used in their crucible system for flanking that sounds like it should improve performance of this module. Defining a polygon, then sweeping through tokens within that polygon. Could also allow for keeping auras from passing through walls.

https://www.twitch.tv/videos/1835904501?t=01h29m52s

**Comment by FionaBrightgrass** [comment]
Hi I ran some performance testing, and a big hit to the performance turns out was token.getActor(). There should be a large improvement this update.
